import type { SectionData, Checkpoint, CheckItem, WorkPhase } from '@/types/closingCheck'

// 현장점검 반별 체크리스트 — 첨부 엑셀(현장점검_반별항목.xlsx) 원본을 그대로 반영.
// 그룹(작업전/작업중/작업후)·순서(No)·입력유형(메모 기준: 사진/숫자/시간/체크) 유지, 문구 원본 그대로.
// mes-v2 'src/lib/closing-items.ts' 의 CLOSING_SECTIONS 와 항목이 1:1로 동일하다.

// 항목의 작업 단계(작업전/작업중/작업후) 결정. phase가 있으면 그대로, 없으면 라벨로 자동 분류.
export function resolvePhase(item: CheckItem): WorkPhase {
  if (item.phase) return item.phase
  const l = item.label
  if (/\(퇴근시\)|종료 시간|마감 시간|퇴근|서류.*전달|일지.*작성/.test(l)) return '작업후'
  if (/작업 전|아침 조회|건강 상태|작업자 배치|출근|위생복/.test(l)) return '작업전'
  return '작업중'
}

export const SECTIONS: SectionData[] = [
  {
    sectionId: "자재반",
    sectionName: "자재반",
    items: [
      { id: "자재반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "자재반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "자재반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "자재반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (입고, 불출, 간반, 재고조사, 발주 )", inputType: "ox" },
      { id: "자재반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "자재반_6", no: 6, category: "작업중", phase: "작업중", label: "육류 해동 시켜 놓았는가? ( 해동 3일 )", inputType: "ox" },
      { id: "자재반_7", no: 7, category: "작업중", phase: "작업중", label: "해동일지 작성 및 해동 스티커 부착 해두었는가?", inputType: "ox" },
      { id: "자재반_8", no: 8, category: "작업후", phase: "작업후", label: "간반 종료 시간", inputType: "time" },
      { id: "자재반_9", no: 9, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "자재반_10", no: 10, category: "작업후", phase: "작업후", label: "출퇴근 기록지, 해동일지, 입고점검표 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "자재반_11", no: 11, category: "작업후", phase: "작업후", label: "(퇴근시) 각 창고별 불은 꺼져 있는가?", inputType: "ox" },
      { id: "자재반_12", no: 12, category: "작업후", phase: "작업후", label: "(퇴근시) 여름 : 에어컨/제습기 작동 ㅇ , 겨울 : 에어컨/제습기 X", inputType: "ox" },
      { id: "자재반_13", no: 13, category: "작업후", phase: "작업후", label: "(발생 시) 반품 처리는 진행 하였는가?", inputType: "ox" },
      { id: "자재반_14", no: 14, category: "작업후", phase: "작업후", label: "원재료 이슈 있는 제품이 있었는가? (품질, 이물, 입고 지연 등)", inputType: "ox" },
      { id: "자재반_15", no: 15, category: "작업후", phase: "작업후", label: "(있었을 경우) 보고 진행 하였는가?", inputType: "ox" },
      { id: "자재반_16", no: 16, category: "작업후", phase: "작업후", label: "각 입고처에서 거래명세서와 타코메타지, 팔레트 전표를 받았는가?", inputType: "ox" },
      { id: "자재반_17", no: 17, category: "작업후", phase: "작업후", label: "재고 품목 중 소비기한 임박 제품이 있는가?", inputType: "ox" },
      { id: "자재반_18", no: 18, category: "작업후", phase: "작업후", label: "재고 품목 중 불용재고가 있는가? 있다면 제품명, 중량 확인 했는가?", inputType: "ox" },
      { id: "자재반_19", no: 19, category: "작업후", phase: "작업후", label: "지게차는 잘 작동 되는가?", inputType: "ox" },
      { id: "자재반_20", no: 20, category: "작업후", phase: "작업후", label: "전동 핸드 자키는 정상 작동 되는가?", inputType: "ox" },
      { id: "자재반_21", no: 21, category: "작업후", phase: "작업후", label: "팔레트는 누워 보관되어 있는가?", inputType: "ox" },
      { id: "자재반_22", no: 22, category: "작업후", phase: "작업후", label: "팔레트는 10단 이상 쌓지 않고 있는가?", inputType: "ox" },
      { id: "자재반_23", no: 23, category: "작업후", phase: "작업후", label: "스피드 도어는 잘 작동 되는가?", inputType: "ox" },
      { id: "자재반_24", no: 24, category: "작업후", phase: "작업후", label: "방화문 도어는 잘 작동 되는가?", inputType: "ox" },
      { id: "자재반_25", no: 25, category: "작업후", phase: "작업후", label: "소방문 앞에 물건은 적재 되어 있는가?", inputType: "ox" },
      { id: "자재반_26", no: 26, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "자재반_27", no: 27, category: "작업후", phase: "작업후", label: "작업대에는 먼지가 없고, 정리정돈이 되어있는가?", inputType: "ox" },
      { id: "자재반_28", no: 28, category: "작업후", phase: "작업후", label: "원재료는 밀봉되어있고, 표시사항이 붙어있는가?", inputType: "ox" },
      { id: "자재반_29", no: 29, category: "작업후", phase: "작업후", label: "냉장,냉동고의 온도는 정상범위인가? (또는 기록으로남기기)", inputType: "ox" },
      { id: "자재반_30", no: 30, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "자재반_31", no: 31, category: "작업후", phase: "작업후", label: "손세정대는 청결하게 관리하였는가?", inputType: "ox" },
      { id: "자재반_32", no: 32, category: "작업후", phase: "작업후", label: "사무공간은 청결하고, 정리정돈이 되어있는가?", inputType: "ox" },
    ],
  },
  {
    sectionId: "전처리반",
    sectionName: "전처리반",
    items: [
      { id: "전처리반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "전처리반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "전처리반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "전처리반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (전전처리, 나물, 간반, 수산/육류 )", inputType: "ox" },
      { id: "전처리반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "전처리반_6", no: 6, category: "작업중", phase: "작업중", label: "ppm 측정하였는가?", inputType: "photo" },
      { id: "전처리반_7", no: 7, category: "작업중", phase: "작업중", label: "잔류염소 측정하였는가?", inputType: "photo" },
      { id: "전처리반_8", no: 8, category: "작업후", phase: "작업후", label: "간반 종료 시간", inputType: "time" },
      { id: "전처리반_9", no: 9, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "전처리반_10", no: 10, category: "작업후", phase: "작업후", label: "출퇴근 기록지, CCP 일지 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "전처리반_11", no: 11, category: "작업후", phase: "작업후", label: "(퇴근시) 위생전실 불은 꺼져 있는가?", inputType: "ox" },
      { id: "전처리반_12", no: 12, category: "작업후", phase: "작업후", label: "(퇴근시) 여름 : 에어컨 제습 O , 겨울 : 에어컨 제습 X 상태인가?", inputType: "ox" },
      { id: "전처리반_13", no: 13, category: "작업후", phase: "작업후", label: "(퇴근시) 물은 잘 잠겨있고, 가스불은 모두 꺼져 있는가?", inputType: "ox" },
      { id: "전처리반_14", no: 14, category: "작업후", phase: "작업후", label: "원재료 이슈 있는 제품이 있었는가? (품질, 이물, 입고 지연 등)\n(있었을 경우) 보고 진행 하였는가?", inputType: "ox" },
      { id: "전처리반_15", no: 15, category: "작업후", phase: "작업후", label: "채고야 3대 (1,2,3호기)는 정상 작동 하는가? (칼날 포함)", inputType: "ox" },
      { id: "전처리반_16", no: 16, category: "작업후", phase: "작업후", label: "무뚝이 1대는 정상 작동 하는가? (칼날 포함)", inputType: "ox" },
      { id: "전처리반_17", no: 17, category: "작업후", phase: "작업후", label: "탈수기 1대는 정상 작동 하는가?", inputType: "ox" },
      { id: "전처리반_18", no: 18, category: "작업후", phase: "작업후", label: "3단 버블 세척기는 정상 작동 하는가? (PPM 측정기 포함)", inputType: "ox" },
      { id: "전처리반_19", no: 19, category: "작업후", phase: "작업후", label: "당근채 기계는 정상 작동 하는가?", inputType: "ox" },
      { id: "전처리반_20", no: 20, category: "작업후", phase: "작업후", label: "감자탈피기, 감자분쇄기는 잘 작동 하는가?", inputType: "ox" },
      { id: "전처리반_21", no: 21, category: "작업후", phase: "작업후", label: "야채 다지기는 잘 작동 하는가?", inputType: "ox" },
      { id: "전처리반_22", no: 22, category: "작업후", phase: "작업후", label: "파채 기계는 잘 작동 하는가?", inputType: "ox" },
      { id: "전처리반_23", no: 23, category: "작업후", phase: "작업후", label: "소독고 및 위생전실은 잘 작동하는가?", inputType: "ox" },
      { id: "전처리반_24", no: 24, category: "작업후", phase: "작업후", label: "조리도구 갯수 파악 했는가? (칼 / 가위 / 감자칼)", inputType: "ox" },
      { id: "전처리반_25", no: 25, category: "작업후", phase: "작업후", label: "트렌치 및 집수조는 청결하게 청소하였는가?", inputType: "ox" },
      { id: "전처리반_26", no: 26, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "전처리반_27", no: 27, category: "작업후", phase: "작업후", label: "작업대에는 이물이 없고, 정리정돈 되어있는가?", inputType: "ox" },
      { id: "전처리반_28", no: 28, category: "작업후", phase: "작업후", label: "원재료는 밀봉되어있고, 표시사항이 붙어있는가?", inputType: "ox" },
      { id: "전처리반_29", no: 29, category: "작업후", phase: "작업후", label: "설비는 이물이 없고, 청결한가?", inputType: "ox" },
      { id: "전처리반_30", no: 30, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "전처리반_31", no: 31, category: "작업후", phase: "작업후", label: "카트에 이물이 없이 청결한가?", inputType: "ox" },
      { id: "전처리반_32", no: 32, category: "작업후", phase: "작업후", label: "소독고는 청결하게 관리하며, 전원이 켜져있는가?", inputType: "ox" },
      { id: "전처리반_33", no: 33, category: "작업후", phase: "작업후", label: "위생전실은 청결하게 관리하였는가?", inputType: "ox" },
    ],
  },
  {
    sectionId: "조리반",
    sectionName: "조리반",
    items: [
      { id: "조리반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "조리반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "조리반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "조리반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (나물류, 볶음류, 조림류, 국탕류, 전 등)", inputType: "ox" },
      { id: "조리반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "조리반_6", no: 6, category: "작업중", phase: "작업중", label: "기름 산가 측정 하였는가?", inputType: "photo" },
      { id: "조리반_7", no: 7, category: "작업중", phase: "작업중", label: "김치 숙성은 숙성존에 잘 보관되고 있는가?", inputType: "photo" },
      { id: "조리반_8", no: 8, category: "작업후", phase: "작업후", label: "간반 종료 시간", inputType: "time" },
      { id: "조리반_9", no: 9, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "조리반_10", no: 10, category: "작업후", phase: "작업후", label: "출퇴근 기록지, CCP 일지 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "조리반_11", no: 11, category: "작업후", phase: "작업후", label: "(퇴근시) 위생전실 불은 꺼져 있는가?", inputType: "ox" },
      { id: "조리반_12", no: 12, category: "작업후", phase: "작업후", label: "(퇴근시) 여름 :제습기 가동 O , 겨울 : 제습기 X 상태인가?", inputType: "ox" },
      { id: "조리반_13", no: 13, category: "작업후", phase: "작업후", label: "(퇴근시) 물은 잘 잠겨있고, 가스불 및 화구는 모두 꺼져 있는가?", inputType: "ox" },
      { id: "조리반_14", no: 14, category: "작업후", phase: "작업후", label: "원재료 이슈 있는 제품이 있었는가? (품질, 이물, 입고 지연 등)\n(있을 경우) 보고 진행 하였는가?", inputType: "ox" },
      { id: "조리반_15", no: 15, category: "작업후", phase: "작업후", label: "폐유는 폐유 보관장소에 잘 보관되고 있는가?", inputType: "ox" },
      { id: "조리반_16", no: 16, category: "작업후", phase: "작업후", label: "설거지 마감은 16시 30분까지 진행하였는가?", inputType: "ox" },
      { id: "조리반_17", no: 17, category: "작업후", phase: "작업후", label: "각 화구 및 전판은 잘 작동 되는가?", inputType: "ox" },
      { id: "조리반_18", no: 18, category: "작업후", phase: "작업후", label: "오븐기는 잘 작동되는가?", inputType: "ox" },
      { id: "조리반_19", no: 19, category: "작업후", phase: "작업후", label: "튀김기는 잘 작동되는가?", inputType: "ox" },
      { id: "조리반_20", no: 20, category: "작업후", phase: "작업후", label: "반죽기는 잘 작동되는가?", inputType: "ox" },
      { id: "조리반_21", no: 21, category: "작업후", phase: "작업후", label: "식기세척기는 잘 작동되는가?", inputType: "ox" },
      { id: "조리반_22", no: 22, category: "작업후", phase: "작업후", label: "릴 호스는 이상없이 잘 작동되는가?", inputType: "ox" },
      { id: "조리반_23", no: 23, category: "작업후", phase: "작업후", label: "소독고 및 위생전실은 잘 작동하는가?", inputType: "ox" },
      { id: "조리반_24", no: 24, category: "작업후", phase: "작업후", label: "조리도구 갯수 파악 했는가? (국자 / 가위 / 스쿱 / 헤라)", inputType: "number" },
      { id: "조리반_25", no: 25, category: "작업후", phase: "작업후", label: "트렌치 및 집수조는 청결하게 청소하였는가?", inputType: "photo" },
      { id: "조리반_26", no: 26, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "조리반_27", no: 27, category: "작업후", phase: "작업후", label: "작업대에는 이물이 없고, 정리정돈 되어있는가?", inputType: "ox" },
      { id: "조리반_28", no: 28, category: "작업후", phase: "작업후", label: "원재료는 밀봉되어있고, 표시사항이 붙어있는가?", inputType: "ox" },
      { id: "조리반_29", no: 29, category: "작업후", phase: "작업후", label: "설비는 이물이 없고, 청결한가?", inputType: "ox" },
      { id: "조리반_30", no: 30, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "조리반_31", no: 31, category: "작업후", phase: "작업후", label: "교반솥의 펠러는 청결하며, 체결상태가 양호한가?", inputType: "ox" },
      { id: "조리반_32", no: 32, category: "작업후", phase: "작업후", label: "세척실 소방구역주변을 정리하였는가?", inputType: "ox" },
      { id: "조리반_33", no: 33, category: "작업후", phase: "작업후", label: "카트에 이물이 없이 청결한가?", inputType: "ox" },
      { id: "조리반_34", no: 34, category: "작업후", phase: "작업후", label: "소독고는 청결하게 관리하며, 전원이 켜져있는가?", inputType: "ox" },
      { id: "조리반_35", no: 35, category: "작업후", phase: "작업후", label: "냉장,냉동고의 온도는 정상범위인가? (또는 기록으로남기기)", inputType: "ox" },
      { id: "조리반_36", no: 36, category: "작업후", phase: "작업후", label: "위생전실은 청결하게 관리하였는가?", inputType: "ox" },
    ],
  },
  {
    sectionId: "내포장반",
    sectionName: "내포장반",
    items: [
      { id: "내포장반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "내포장반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "내포장반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "내포장반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (나물류, 볶음류, 조림류, 국탕류, 전 등)", inputType: "ox" },
      { id: "내포장반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "내포장반_6", no: 6, category: "작업후", phase: "작업후", label: "간반 종료 시간", inputType: "time" },
      { id: "내포장반_7", no: 7, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "내포장반_8", no: 8, category: "작업후", phase: "작업후", label: "출퇴근 기록지, CCP 일지 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "내포장반_9", no: 9, category: "작업후", phase: "작업후", label: "전처리실 위생전실을 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_10", no: 10, category: "작업후", phase: "작업후", label: "전처리실 배기가 꺼져있는가?", inputType: "ox" },
      { id: "내포장반_11", no: 11, category: "작업후", phase: "작업후", label: "(여름) 전처리실 에어컨 가동은 되고 있는가?", inputType: "ox" },
      { id: "내포장반_12", no: 12, category: "작업후", phase: "작업후", label: "(여름) 전처리실-조리실 사이 문이 열려있는가?", inputType: "ox" },
      { id: "내포장반_13", no: 13, category: "작업후", phase: "작업후", label: "(겨울) 전처리실 냉난방기는 꺼졌는가?", inputType: "ox" },
      { id: "내포장반_14", no: 14, category: "작업후", phase: "작업후", label: "조리반 배기가 꺼져있는가?", inputType: "ox" },
      { id: "내포장반_15", no: 15, category: "작업후", phase: "작업후", label: "(겨울) 반 별 유리문은 모두 닫혀있는가?", inputType: "ox" },
      { id: "내포장반_16", no: 16, category: "작업후", phase: "작업후", label: "(여름) 제습기가 2대 모두 정상적으로 가동되고 있는가?", inputType: "ox" },
      { id: "내포장반_17", no: 17, category: "작업후", phase: "작업후", label: "(겨울) 제습기가 2대 모두 꺼졌는가?", inputType: "ox" },
      { id: "내포장반_18", no: 18, category: "작업후", phase: "작업후", label: "세척실, 냉각실, 냉장고는 모두 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_19", no: 19, category: "작업후", phase: "작업후", label: "모든 작업공간의 소등을 한 번 더 확인하였는가?", inputType: "ox" },
      { id: "내포장반_20", no: 20, category: "작업후", phase: "작업후", label: "소스실, 국탕류 조리실 문은 닫혀있는가? (에어커튼)", inputType: "ox" },
      { id: "내포장반_21", no: 21, category: "작업후", phase: "작업후", label: "3층 창고 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_22", no: 22, category: "작업후", phase: "작업후", label: "탈의실 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_23", no: 23, category: "작업후", phase: "작업후", label: "세탁실 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_24", no: 24, category: "작업후", phase: "작업후", label: "화장실 소등이 되었는가?", inputType: "ox" },
      { id: "내포장반_25", no: 25, category: "작업후", phase: "작업후", label: "화장실 거울 조명이 꺼졌는가?", inputType: "ox" },
      { id: "내포장반_26", no: 26, category: "작업후", phase: "작업후", label: "에어콤프레샤 전원은 꺼졌는가?", inputType: "ox" },
      { id: "내포장반_27", no: 27, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "내포장반_28", no: 28, category: "작업후", phase: "작업후", label: "작업대에는 이물이 없고, 정리정돈이 되어있는가?", inputType: "ox" },
      { id: "내포장반_29", no: 29, category: "작업후", phase: "작업후", label: "원재료는 밀봉되어있고, 표시사항이 붙어있는가?", inputType: "ox" },
      { id: "내포장반_30", no: 30, category: "작업후", phase: "작업후", label: "냉장고의 온도는 정상범위인가? (또는 기록으로남기기)", inputType: "ox" },
      { id: "내포장반_31", no: 31, category: "작업후", phase: "작업후", label: "트렌치 및 집수조는 청결하게 청소하였는가?", inputType: "photo" },
      { id: "내포장반_32", no: 32, category: "작업후", phase: "작업후", label: "설비는 이물이 없고, 청결한가?", inputType: "ox" },
      { id: "내포장반_33", no: 33, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "내포장반_34", no: 34, category: "작업후", phase: "작업후", label: "카트에 이물이 없이 청결한가?", inputType: "ox" },
      { id: "내포장반_35", no: 35, category: "작업후", phase: "작업후", label: "소독고는 청결하게 관리하며, 전원이 켜져있는가?", inputType: "ox" },
      { id: "내포장반_36", no: 36, category: "작업후", phase: "작업후", label: "위생전실은 청결하게 관리하였는가?", inputType: "ox" },
      { id: "내포장반_37", no: 37, category: "작업후", phase: "작업후", label: "에어샤워기 내부를 청소하였는가?", inputType: "ox" },
    ],
  },
  {
    sectionId: "외포장반",
    sectionName: "외포장반",
    items: [
      { id: "외포장반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "외포장반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "외포장반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "외포장반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (반찬 분류, 피킹, 패킹 등)", inputType: "ox" },
      { id: "외포장반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "외포장반_6", no: 6, category: "작업후", phase: "작업후", label: "반찬 마감 시간", inputType: "time" },
      { id: "외포장반_7", no: 7, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "외포장반_8", no: 8, category: "작업후", phase: "작업후", label: "출퇴근 기록지, 지게차 관련, 운반관리 일지 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "외포장반_9", no: 9, category: "작업후", phase: "작업후", label: "(퇴근시) 자재실 및 외포장실 불은 꺼져 있는가?", inputType: "ox" },
      { id: "외포장반_10", no: 10, category: "작업후", phase: "작업후", label: "(퇴근시) 방화문 도어는 잘 닫았는가?", inputType: "ox" },
      { id: "외포장반_11", no: 11, category: "작업후", phase: "작업후", label: "(퇴근시) 지게차는 충전 단자에 잘 꽂았는가?", inputType: "ox" },
      { id: "외포장반_12", no: 12, category: "작업후", phase: "작업후", label: "(퇴근시) 쿨러 작동이 이상없이 되고 있는가?", inputType: "ox" },
      { id: "외포장반_13", no: 13, category: "작업후", phase: "작업후", label: "(퇴근시) 4층 불은 다 꺼져 있는가?", inputType: "ox" },
      { id: "외포장반_14", no: 14, category: "작업후", phase: "작업후", label: "(퇴근시) 지하 1층 불은 꺼져 있는가?", inputType: "ox" },
      { id: "외포장반_15", no: 15, category: "작업후", phase: "작업후", label: "(퇴근시) 1층 탈의실 및 화장실, 복도 불은 꺼져 있는가?", inputType: "ox" },
      { id: "외포장반_16", no: 16, category: "작업후", phase: "작업후", label: "(퇴근시) 여름 : 제습기 작동은 되고 있는가?", inputType: "ox" },
      { id: "외포장반_17", no: 17, category: "작업후", phase: "작업후", label: "완제품 이슈 있는 제품이 있었는가? (필름 터짐,오염, 수량 부족 등)\n(있을 경우) 보고 진행 하였는가?", inputType: "ox" },
      { id: "외포장반_18", no: 18, category: "작업후", phase: "작업후", label: "일지 작성 등을 모두 작성하였는가?", inputType: "ox" },
      { id: "외포장반_19", no: 19, category: "작업후", phase: "작업후", label: "스파이럴 레일은 이상없는가?", inputType: "ox" },
      { id: "외포장반_20", no: 20, category: "작업후", phase: "작업후", label: "에어 충진기는 이상없는가?", inputType: "ox" },
      { id: "외포장반_21", no: 21, category: "작업후", phase: "작업후", label: "밴딩기는 이상없는가?", inputType: "ox" },
      { id: "외포장반_22", no: 22, category: "작업후", phase: "작업후", label: "ZPPS 작동은 잘 되는가?", inputType: "ox" },
      { id: "외포장반_23", no: 23, category: "작업후", phase: "작업후", label: "WES 작동은 잘 되는가?", inputType: "ox" },
      { id: "외포장반_24", no: 24, category: "작업후", phase: "작업후", label: "전동 핸드 자키 잘 작동되는가?", inputType: "ox" },
      { id: "외포장반_25", no: 25, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "외포장반_26", no: 26, category: "작업후", phase: "작업후", label: "작업대에는 먼지가 없고, 정리정돈이 되어있는가?", inputType: "ox" },
      { id: "외포장반_27", no: 27, category: "작업후", phase: "작업후", label: "완제품은 라벨이 붙어있고, 정리정돈이 되어있는가?", inputType: "ox" },
      { id: "외포장반_28", no: 28, category: "작업후", phase: "작업후", label: "냉장,냉동고의 온도는 정상범위인가? (또는 기록으로남기기)", inputType: "ox" },
      { id: "외포장반_29", no: 29, category: "작업후", phase: "작업후", label: "설비는 이물이 없고, 청결한가?", inputType: "ox" },
      { id: "외포장반_30", no: 30, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "외포장반_31", no: 31, category: "작업후", phase: "작업후", label: "카트에 먼지가 없이 청결한가?", inputType: "ox" },
      { id: "외포장반_32", no: 32, category: "작업후", phase: "작업후", label: "소독고는 청결하게 관리하며, 전원이 켜져있는가?", inputType: "ox" },
      { id: "외포장반_33", no: 33, category: "작업후", phase: "작업후", label: "손세정대는 청결하게 관리하였는가?", inputType: "ox" },
      { id: "외포장반_34", no: 34, category: "작업후", phase: "작업후", label: "사무공간은 청결하고, 정리정돈이 되어있는가?", inputType: "ox" },
    ],
  },
  {
    sectionId: "소스국탕반",
    sectionName: "소스국탕반",
    items: [
      { id: "소스국탕반_1", no: 1, category: "작업전", phase: "작업전", label: "출근 인원 체크", inputType: "ox" },
      { id: "소스국탕반_2", no: 2, category: "작업전", phase: "작업전", label: "작업 전 작업자 건강 상태 체크를 하였는가?", inputType: "ox" },
      { id: "소스국탕반_3", no: 3, category: "작업전", phase: "작업전", label: "현장 아침 조회 진행하였는가? (생산 특이사항, 안전 구호 등 )", inputType: "ox" },
      { id: "소스국탕반_4", no: 4, category: "작업전", phase: "작업전", label: "작업자 배치가 되었는가? (반찬 분류, 피킹, 패킹 등)", inputType: "ox" },
      { id: "소스국탕반_5", no: 5, category: "작업전", phase: "작업전", label: "위생복은 청결하게 관리되고 있는가?", inputType: "ox" },
      { id: "소스국탕반_6", no: 6, category: "작업중", phase: "작업중", label: "라벨 스티커 날짜 및 소비기한 확인 하였는가?", inputType: "ox" },
      { id: "소스국탕반_7", no: 7, category: "작업중", phase: "작업중", label: "생산시 관리자 맛 점검을 받았는가?", inputType: "ox" },
      { id: "소스국탕반_8", no: 8, category: "작업중", phase: "작업중", label: "생산시 염도, 당도, 산가 측정 하였는가?", inputType: "ox" },
      { id: "소스국탕반_9", no: 9, category: "작업중", phase: "작업중", label: "가열, 산가 CCP , 배합 일지는 작성 완료하였는가?", inputType: "ox" },
      { id: "소스국탕반_10", no: 10, category: "작업후", phase: "작업후", label: "간반 종료 시간", inputType: "time" },
      { id: "소스국탕반_11", no: 11, category: "작업후", phase: "작업후", label: "작업 종료 시간(퇴근 시간)", inputType: "time" },
      { id: "소스국탕반_12", no: 12, category: "작업후", phase: "작업후", label: "출퇴근 기록지, CCP 일지 등 서류는 전달 완료하였는가?", inputType: "ox" },
      { id: "소스국탕반_13", no: 13, category: "작업후", phase: "작업후", label: "(퇴근시) 위생전실 불은 꺼져 있는가?", inputType: "ox" },
      { id: "소스국탕반_14", no: 14, category: "작업후", phase: "작업후", label: "(퇴근시) 모든 생산실, 냉장고 등 불 꺼져 있는가?", inputType: "ox" },
      { id: "소스국탕반_15", no: 15, category: "작업후", phase: "작업후", label: "(퇴근시) 여름 :에어컨 제습 가동 O , 겨울 : 에어컨 제습 X 상태인가?", inputType: "ox" },
      { id: "소스국탕반_16", no: 16, category: "작업후", phase: "작업후", label: "(퇴근시) 물은 잘 잠겨있고, 가스불은 모두 꺼져 있는가?", inputType: "ox" },
      { id: "소스국탕반_17", no: 17, category: "작업후", phase: "작업후", label: "원재료 이슈 있는 제품이 있었는가? (품질, 이물, 입고 지연 등)\n(있을 경우) 보고 진행 하였는가?", inputType: "ox" },
      { id: "소스국탕반_18", no: 18, category: "작업후", phase: "작업후", label: "원재료는 1층에서 불출 하고 남은 제품은 자재 반납 하였는가?", inputType: "ox" },
      { id: "소스국탕반_19", no: 19, category: "작업후", phase: "작업후", label: "각 국솥은 잘 작동 되는가?", inputType: "ox" },
      { id: "소스국탕반_20", no: 20, category: "작업후", phase: "작업후", label: "수직밴드 실러는 잘 작동되는가?", inputType: "ox" },
      { id: "소스국탕반_21", no: 21, category: "작업후", phase: "작업후", label: "소스 충진기는 잘 작동되는가?", inputType: "ox" },
      { id: "소스국탕반_22", no: 22, category: "작업후", phase: "작업후", label: "파우치 기계는 잘 작동되는가?", inputType: "ox" },
      { id: "소스국탕반_23", no: 23, category: "작업후", phase: "작업후", label: "옹심이 반죽기는 잘 작동되는가?", inputType: "ox" },
      { id: "소스국탕반_24", no: 24, category: "작업후", phase: "작업후", label: "금속검출기는 잘 작동되는가?", inputType: "ox" },
      { id: "소스국탕반_25", no: 25, category: "작업후", phase: "작업후", label: "대용량 기계는 잘 작동되는가? (운영시)", inputType: "ox" },
      { id: "소스국탕반_26", no: 26, category: "작업후", phase: "작업후", label: "소독고 및 위생전실은 잘 작동하는가?", inputType: "ox" },
      { id: "소스국탕반_27", no: 27, category: "작업후", phase: "작업후", label: "조리도구 갯수 파악 했는가? (국자 / 가위)", inputType: "ox" },
      { id: "소스국탕반_28", no: 28, category: "작업후", phase: "작업후", label: "트렌치 및 집수조는 청결하게 청소하였는가?", inputType: "ox" },
      { id: "소스국탕반_29", no: 29, category: "작업후", phase: "작업후", label: "작업장 바닥은 청결하게 청소하였는가?", inputType: "ox" },
      { id: "소스국탕반_30", no: 30, category: "작업후", phase: "작업후", label: "작업대에는 이물이 없고, 정리정돈 되어있는가?", inputType: "ox" },
      { id: "소스국탕반_31", no: 31, category: "작업후", phase: "작업후", label: "원재료는 밀봉되어있고, 표시사항이 붙어있는가?", inputType: "ox" },
      { id: "소스국탕반_32", no: 32, category: "작업후", phase: "작업후", label: "설비는 이물이 없고, 청결한가?", inputType: "ox" },
      { id: "소스국탕반_33", no: 33, category: "작업후", phase: "작업후", label: "위험물은 보관장소에 보관하였는가?", inputType: "ox" },
      { id: "소스국탕반_34", no: 34, category: "작업후", phase: "작업후", label: "교반솥의 펠러는 청결하며, 체결상태가 양호한가?", inputType: "ox" },
      { id: "소스국탕반_35", no: 35, category: "작업후", phase: "작업후", label: "카트에 이물이 없이 청결한가?", inputType: "ox" },
      { id: "소스국탕반_36", no: 36, category: "작업후", phase: "작업후", label: "소독고는 청결하게 관리하며, 전원이 켜져있는가?", inputType: "ox" },
      { id: "소스국탕반_37", no: 37, category: "작업후", phase: "작업후", label: "냉동고의 온도는 정상범위인가? (또는 기록으로남기기)", inputType: "ox" },
      { id: "소스국탕반_38", no: 38, category: "작업후", phase: "작업후", label: "위생전실은 청결하게 관리하였는가?", inputType: "ox" },
    ],
  },
]

// 점표(체크포인트) — 각 반은 QR 코드와 1:1 매칭되며 스캔으로 활성화된다.
export const CHECKPOINTS: Checkpoint[] = SECTIONS.map((s) => ({
  id: s.sectionId,
  name: s.sectionName,
  location: s.sectionName,
  qrCode: `QR-${s.sectionId}`,
  items: s.items,
}))

// 항목 수 검증 (엑셀 기준 체크섬)
export function validateSections(): void {
  const expected: Record<string, number> = {
    "자재반": 32,
    "전처리반": 33,
    "조리반": 36,
    "내포장반": 37,
    "외포장반": 34,
    "소스국탕반": 38,
  }
  const ids = new Set<string>()
  SECTIONS.forEach((s) => {
    const actual = s.items.length
    const exp = expected[s.sectionId] ?? '?'
    if (actual !== exp) console.warn(`[체크리스트 검증] ${s.sectionName}: 예상 ${exp}, 실제 ${actual}`)
    else console.log(`[체크리스트 검증] ${s.sectionName}: ${actual}개 ✓`)
    s.items.forEach((i) => { if (ids.has(i.id)) console.warn(`중복 ID: ${i.id}`); ids.add(i.id) })
  })
  console.log(`[체크리스트 검증] 합계: ${SECTIONS.reduce((a, s) => a + s.items.length, 0)}개`)
}
